language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-suit-lite' ]; then cd .. && eval "mv $currentfolder generator-suit-lite" && cd generator-suit-lite; fi

